spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

server:
  port: 8080

# AWS S3 Configuration
aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:adobe-images}
    region: ${AWS_S3_REGION:us-east-1}
    endpoint: ${AWS_S3_ENDPOINT:http://localhost:4566}
    access-key: ${AWS_S3_ACCESS_KEY:test}
    secret-key: ${AWS_S3_SECRET_KEY:test}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Docker profile
---
spring:
  config:
    activate:
      on-profile: docker

aws:
  s3:
    endpoint: http://localstack:4566

logging:
  level:
    root: INFO
    com.mahesh.adobe: DEBUG